on: [pull_request]

name: IntegrationTests

jobs:
  integration_tests_mosquitto:
    name: Integration tests with mosquitto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build embedded
        run: cargo build --target thumbv7em-none-eabihf --features "no_std" --no-default-features

      - name: Install Mosquitto
        run: |
          sudo apt-get update
          sudo apt-get install mosquitto
          sudo service mosquitto stop

      - name: Configure & Start Mosquitto
        run: |
          cp .ci/mqtt_pass_plain.txt .ci/mqtt_pass_hashed.txt
          chmod 700 .ci/mqtt_pass_hashed.txt
          mosquitto_passwd -U .ci/mqtt_pass_hashed.txt
          mosquitto -c .ci/mosquitto.conf -d

      - name: Run integration-tests tests
        run: RUST_LOG=trace cargo test integration

  integration_tests_hive:
    name: Integration tests with HiveMQ
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build embedded
        run: cargo build --target thumbv7em-none-eabihf --features "no_std" --no-default-features

      - name: Start HiveMQ
        run: |
          curl -LO https://github.com/hivemq/hivemq-community-edition/releases/download/2021.3/hivemq-ce-2021.3.zip
          unzip hivemq-ce-2021.3.zip
          curl -LO https://www.hivemq.com/releases/extensions/hivemq-file-rbac-extension-4.4.0.zip
          unzip hivemq-file-rbac-extension-4.4.0.zip
          mv hivemq-file-rbac-extension hivemq-ce-2021.3/extensions
          cp .ci/hive_cred.xml hivemq-ce-2021.3/extensions/hivemq-file-rbac-extension/credentials.xml
          cp .ci/hive_extension_config.xml hivemq-ce-2021.3/extensions/hivemq-file-rbac-extension/extension-config.xml
          hivemq-ce-2021.3/bin/run.sh &

      - name: Run integration-tests tests
        run: RUST_LOG=trace cargo test integration