on: [pull_request]

name: UnitTests

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run unit tests
        run: RUST_LOG=trace cargo test unit